# Generated by Django 3.0.4 on 2020-04-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
