# Generated by Django 3.0.4 on 2020-04-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0005_auto_20200331_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationChain',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='transformations')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
    ]
