# Generated by Django 3.0.4 on 2020-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0002_auto_20200403_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationchain',
            name='extension',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='transformationchain',
            name='mime',
            field=models.CharField(default='', max_length=64),
        ),
    ]
